export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";

export const FETCH_CRYPTOCURRENCIES_REQUEST = "FETCH_CRYPTOCURRENCIES_REQUEST";
export const FETCH_CRYPTOCURRENCIES_SUCCESS = "FETCH_CRYPTOCURRENCIES_SUCCESS";
export const FETCH_CRYPTOCURRENCIES_FAILED = "FETCH_CRYPTOCURRENCIES_FAILED";

export const ON_TRANSACTION = "ON_TRANSACTION";
